name: Build radare2 for iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone radare2
        run: git clone https://github.com/radareorg/radare2.git
      - name: Build for iOS
        run: |
          cd radare2
          ./sys/ios-sdk.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: radare2-ios-arm64
          path: radare2/binr/radare2/radare2
